##
##  Makefile -- Build procedure for sample auth_hard Apache module
##  Autogenerated via ``apxs -n auth_hard -g''.
##

builddir=.
top_srcdir=/opt/local/apache2
top_builddir=$(top_srcdir)
include $(top_srcdir)/build/special.mk

#   the used tools
APXS=$(top_srcdir)/bin/apxs
APACHECTL=$(top_srcdir)/bin/apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
INCLUDES=-I/Users/steven/Src/general/SQLAPI/include
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_auth_hard.o mod_auth_hard.lo mod_auth_hard.slo mod_auth_hard.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/auth_hard

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

