##
##  Makefile -- Build procedure for sample auth Apache module
##  Autogenerated via ``apxs -n auth -g''.
##

builddir=.
top_srcdir=/opt/local/apache2
top_builddir=$(top_srcdir)
include $(top_srcdir)/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
INCLUDES=-I/root/SQLAPI/include
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_auth.o mod_auth.lo mod_auth.slo mod_auth.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/auth

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

